name: Public-Resume-CI

on: 
  push:
    paths:
        - 'resume/**'
        - 'tran-xuantu.tex'
      branches:
        - main

jobs:
  auto-resume-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: xtutran/public-resume@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        FILE_NAME: 'tran-xuantu.tex'