name: Public-Resume-CI

on: 
  push:
    paths:
      - '.github/**'
      - 'resume/**'
      - 'tran-xuantu.tex'
      - Dockerfile
    branches:
      - main

jobs:
  auto-resume-job:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - uses: xtutran/public-resume@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        FILE_NAME: 'tran-xuantu.tex'